#!/usr/bin/python

import sqlite3 as lite
import csv
import cgi
import sys

print "Content-type: text/html"
print
form = cgi.FieldStorage()

if form.has_key('id'):
	id = form['id'].value
else:
	id=""
	
con = lite.connect('test.db')  

con.row_factory = lite.Row
       
cur = con.cursor() 
string="SELECT * FROM answer WHERE test_id=\'%s\';" % (id)
cur.execute(string)
rows = cur.fetchall()


try:
	f=open('output.csv', 'wb')
	writer = csv.writer(f)
	writer.writerow([ i[0] for i in cur.description ]) # heading row
	for row in rows:
		writer.writerow([row["id"],row["test_id"],row["stfirstn"],row["stlastn"],row["stcode"],row["stemail"],row["etime"],row["a0"],row["a1"],row["a2"],row["a3"],row["a4"],row["a5"],row["a6"],row["a7"],row["a8"],row["a9"],row["a10"],row["a11"],row["a12"],row["a13"],row["a14"],row["a15"],row["a16"],row["a17"],row["a18"],row["a19"],row["a20"],row["a21"],row["a22"],row["a23"],row["a24"],row["a25"],row["a26"],row["a27"],row["a28"],row["a29"],row["a30"]])
	f.close()
except Exception, e:
	print e

	


